import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
df=pd.read_csv('testmarks1.csv')
rno=np.array(df['RollNo'])
eds=np.array(df['EDS'])
son=np.array(df['SON'])
dt=np.array(df['DT'])
et=np.array(df['ET'])
sub=("EDS","SON","DT","ET")
mylabels=["EDS","SON","DT","ET"]
mycolors=["red","black","blue","green"]
mycolors1=["m","y","c","k"]
print(df)
max=[]
max.append(df['EDS'].max())
max.append(df['SON'].max())
max.append(df['DT'].max())
max.append(df['ET'].max())
print("MAX MARKS:",max)
min=[]
min.append(df['EDS'].min())
min.append(df['SON'].min())
min.append(df['DT'].min())
min.append(df['ET'].min())
print("MIN MARKS:",min)
avg=[]
avg.append(df['EDS'].mean())
avg.append(df['SON'].mean())
avg.append(df['DT'].mean())
avg.append(df['ET'].mean())
print("AVERAGE MARKS:",avg)
mid=[]
mid.append(df['EDS'].median())
mid.append(df['SON'].median())
mid.append(df['DT'].median())
mid.append(df['ET'].median())
print("MEDIAN VALUES:",mid)
var=[]
var.append(df['EDS'].var())
var.append(df['SON'].var())
var.append(df['DT'].var())
var.append(df['ET'].var())
print("Variance:",var)
sd=[]
sd.append(df['EDS'].std())
sd.append(df['SON'].std())
sd.append(df['DT'].std())
sd.append(df['ET'].std())
print("Standard Deviation:",sd)
plt.figure(figsize=(20,10))
plt.subplot(2,5,1)
plt.plot(rno,eds,color='r')
plt.xlabel("ROLL NO.")
plt.ylabel("MARKS")
plt.title("EDS MARKS")
plt.subplot(2,5,2)
plt.bar(rno,son,color='y')
plt.xlabel("ROLL NO.")
plt.ylabel("MARKS")
plt.title("SON MARKS")
plt.subplot(2,5,3)
plt.plot(rno,dt,color='b')
plt.xlabel("ROLL NO.")
plt.ylabel("MARKS")
plt.title("DT MARKS")
plt.subplot(2,5,4)
plt.scatter(rno,et,color='g')
plt.xlabel("ROLL NO.")
plt.ylabel("MARKS")
plt.title("ET MARKS")
plt.subplot(2,5,5)
plt.bar(sub,max)
plt.xlabel("SUBJECT")
plt.ylabel("MARKS")
plt.title("MAX MARKS")
plt.subplot(2,5,6)
plt.bar(sub,min,color="k")
plt.xlabel("SUBJECT")
plt.ylabel("MARKS")
plt.title("MIN MARKS")
plt.subplot(2,5,7)
plt.pie(avg,labels=mylabels,colors=mycolors)
plt.legend(title="SUBJECTS")
plt.title("AVERAGE MARKS")
plt.subplot(2,5,8)
plt.pie(avg,labels=mylabels,colors=mycolors1)
plt.legend(title="SUBJECTS")
plt.title("MID MARKS")
plt.subplot(2,5,9)
plt.bar(sub,var,color="r")
plt.xlabel("SUBJECT")
plt.ylabel("VARIANCE")
plt.title("VARIANCE OF MARKS")
plt.subplot(2,5,10)
plt.plot(sub,var,color="k")
plt.xlabel("SUBJECT")
plt.ylabel("Standard Deviation")
plt.title("Standard Deviation of Marks")
plt.show()
OUTPUT-
