import numpy as np
math=np.array([85, 92, 78, 90, 88])
eng=np.array([80, 75, 92, 85, 78])
sci=np.array([90, 88, 92, 80, 85])
data=np.array([math, eng, sci])
print("Data :\n",data)
print("\nMatrix Operation :")
tr = np.transpose(data)
print("\ntranspose :\n",tr)
m=np.mean(data, axis=1)
print("\nMean in Row :",m)
m=np.mean(data, axis=0)
print("\nMean in Column :",m)
s=np.sum(data)
print("\nTotal marks :",s)
print("\nHorizontal and vertical stacking of Numpy Arrays")
math2=np.array([95, 88, 90, 82, 85])
eng2=np.array([92, 85, 80, 78, 90])
sci2=np.array([88, 92, 85, 80, 90])
data2=[math2,eng2,sci2]
Hstack=np.hstack(data)
print("\nHorizontal stacking is: \n",Hstack)
Vstack=np.vstack(data2)
print("\nVertical stacking is: \n",Vstack)
print("\nCustom sequence generation")
seq=np.arange(1, 10, 2)
print("Generated Sequence",seq)
ran=np.random.randint(0, 10, 5)
print("Generated random Sequence",ran)
print("\nArithmatic and Statistical Operations, Mathematical Operations,Bitwise Operations ")
a=data+5
print("\nAddition :\n",a)
m=np.min(data,axis=1)
print("\nMinimum in Row :",m)
m=np.min(data,axis=0)
print("\nMinimum in Column :",m)
m=np.max(data,axis=1)
print("\nMaxmum in Row :",m)
m=np.max(data,axis=0)
print("\nMaxmum in Column :",m)
e=np.exp(data)
print("\nExponential :\n",e)
b=data&90
print("\nBitwise and :\n",b)
print("\n5)Copying and viewing arrays")
co=data.copy()
print("\nCopying arrays :\n",co)
vi=data.view()
print("\nViewing arrays :\n",vi)
8] [80 75 92 85 78] [90 88 92 80 85]]
