import pandas as pd
df=pd.read_csv("grainsales.csv",delimiter=",")
month=df.groupby('Months')['Sales'].sum().idxmax()
print("\nMaximum sales are done in the month of: ",month)
sales=df.groupby('Months')['Sales'].sum().max()
print("\nThe earning made in that month is: ",sales)
Max_sales=df.groupby('GrainName')['Sales'].sum().idxmax()
print("\nThe product who sold the most is: ",Max_sales)
City=df.groupby('City')['Sales'].sum().idxmax()
print("\nThe city which sold the most products: ",City)
Min_sales=df.groupby('Months')['Sales'].sum().idxmin()
print("\nMinimum sales are done in the month: ",Min_sales)
Mean=df['Sales'].mean()
print("\nMean of all the sales is: ",Mean)
